language: node_js
node_js:
  - "11"
cache:
  directories:
    - "node_modules"
install:
  - npm install -g vuepress
script:
  - npm run build
notifications:
  email: false

after_script:
  - git init
  - git config user.name "yandixuan"
  - git config user.email "451868992@qq.com"
  - git add docs/
  - git commit -m "Update docs"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:doc

branches:
  only:
    - master
env:
  global:
    - GH_REF=github.com/yandixuan/yandixuan.github.io.git
