language: node_js
node_js:
  - "11"
cache:
  yarn: true
  directories:
    - "node_modules"

branches:
  only:
    - master

env:
  global:
    - GH_REF=github.com/yandixuan/yandixuan.github.io.git

before_install:
  - export TZ=Asia/Shanghai

script:
  - yarn run build

after_script:
  - git clone https://${GH_REF} ./old-docs
  - cp -r ./old-docs/.git ./docs
  - cd ./docs
  - git config user.name "yandixuan"
  - git config user.email "451868992@qq.com"
  - git add -A
  - git commit -m "deploy at `date +\"%Y-%m-%d %H:%M:%S\"`"
  - git push --force --quiet "https://yandixuan:${GH_TOKEN}@${GH_REF}" master:gh-pages
